
FROM nginx:latest

# WORKDIR /usr/share/nginx
# COPY nginx.conf nginx.conf
# COPY nginx.conf /etc/nginx/nginx.conf
COPY dist/emp-app /usr/share/nginx/html

# WORKDIR /etc/nginx/ssl
# VOLUME ./ssl /etc/nginx/ssl
