import{ MatButtonModule, 
         MatCheckboxModule,
         MatToolbarModule,
         MatCardModule,
         MatSelectModule,
         MatInputModule,
         MatDialogModule,
         MatRippleModule,
         MatTableModule,
         MatDatepickerModule,
         MatNativeDateModule,
         MatSnackBarModule} from '@angular/material';
         import {MatIconModule} from '@angular/material/icon';
import { NgModule } from '@angular/core';

@NgModule({
    imports:[ MatButtonModule,
         MatCheckboxModule,
         MatToolbarModule,
         MatCardModule,
         MatSelectModule,
         MatCardModule,
         MatInputModule,
         MatIconModule,
         MatDialogModule,
         MatRippleModule,
         MatTableModule,
         MatDatepickerModule,
         MatNativeDateModule,
         MatSnackBarModule ],

    exports:[ MatButtonModule, 
        MatCheckboxModule,
        MatToolbarModule,
        MatCardModule,
        MatSelectModule,
        MatCardModule,
        MatInputModule,
        MatIconModule,
        MatDialogModule,
        MatRippleModule,
        MatTableModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatSnackBarModule],
})
export class MaterialModule{}