

version: "2"
services:
  app:
    container_name: app
    image: back:1
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"